# Generated by Django 4.0.4 on 2022-08-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_productinbasket_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='product_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
